from pathlib import Path
import json
from jsonschema import Draft202012Validator
R=Path.cwd();B=R/'docs/atomic_reionization_handoff_20261004_v1';P=R/'.cuh/fastest-track/REI-F08-PAIRED';d=json.loads((P/'atomic-domain-final-assessment.json').read_text());f=json.loads((B/'runtime_returns/REI-F08.json').read_text());assert f['state']=='completed'
schema=json.loads((B/'common/RETURN_CONTRACT.schema.json').read_text());target=B/'runtime_returns/REI-F09.json'
r={'task_id':'REI-F09','state':'blocked','input_identity':{'baseline':'runtime_returns/REI-F08.json','scenario_sha256':d['paired_scenario_sha256'],'provider_receipts':d['provider_read_receipts']},'changed_paths':[str(target.relative_to(R)),'docs/atomic_reionization_handoff_20261004_v1/runtime_returns/APPLICATION_CLOSEOUT.json'],'commands':[{'command':'python3 .cuh/fastest-track/REI-F08-PAIRED/assess_atomic_domain_final.py','exit_code':0,'evidence_path':'docs/atomic_reionization_handoff_20261004_v1/runtime_returns/evidence/F08_paired/atomic-domain-final-assessment.json'}],'artifacts':['runtime_returns/evidence/F08_paired/atomic-domain-final-assessment.json','runtime_returns/evidence/F08_successors/SUCCESSOR_DAG_STATE.json'],'claim':{'basis':d,'ceiling':'No optional atomic sensitivity campaign executed; OFF baseline is scoped numerical evidence, not provider F3 completion or negligibility'},'blocker':{'kind':'EXTERNAL_PROVIDER_DOMAIN_AND_BINDING_BLOCKED','FT03_common_intersection':'EMPTY_SET','S0_common_intersection':'EMPTY_SET','HH_owner_binding_ready':False,'He_F2_global_return_accepted':False,'next_executable_condition':d['next_executable_condition']},'next_task':None,'scientific_admission':'HOLD'}
Draft202012Validator(schema).validate(r);target.write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
s=B/'runtime_returns/EXECUTION_STATE.json';state=json.loads(s.read_text());state['runtime_results']=[x for x in state['runtime_results'] if x['task_id']!='REI-F09']+[{'task_id':'REI-F09','state':'blocked','receipt':'REI-F09.json'}];state.update({'next_codex_task':None,'next_task':None,'execution_status':'REACHABLE_OWNER_WORK_COMPLETED_EXTERNAL_INPUTS_BLOCKED','F09_atomic_sensitivity':'BLOCKED_EMPTY_COMMON_DOMAIN_AND_EXTERNAL_BINDING','L01':'DORMANT_NO_SELECTED_EXTENSION','scientific_admission':'HOLD'});s.write_text(json.dumps(state,indent=2)+'\n')
close={'state':'REACHABLE_OWNER_DAG_COMPLETED_WITH_EXPLICIT_EXTERNAL_BLOCKERS','F08':'15 actual independently checked prescribed histories; 248000 accepted selected trials','failed_T2_candidates':'64000 additional accepted trials preserved; not reset or admitted','successor_returns':'evidence/F08_successors/SUCCESSOR_DAG_STATE.json','F09':'blocked; no common FT03/GM25 domain and no accepted optional provider binding','HH_F3_HE_F3':'pending actual shared optional campaign; no duplicate campaign launched','L01':'dormant without selected extension inputs','scientific_admission':'HOLD','direct_chat_delivery':'UNDELIVERED_NO_BROWSER_AVAILABLE','native_tokens':10419630,'native_dispatches':4,'additional_host_cost':'NOT_MEASURED','git_delivery':'PENDING_ACTUAL_PUBLICATION_RECEIPT'};(B/'runtime_returns/APPLICATION_CLOSEOUT.json').write_text(json.dumps(close,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'status':'SCOPED_DAG_RETURN_CONTRACT_PASS','F09':'blocked','physical_admission':'HOLD'}))
