"""Return existing F08/F05 evidence to successor DAG owners without science replay."""
from pathlib import Path
import json,gzip,hashlib
ROOT=Path.cwd();P=ROOT/'.cuh/fastest-track/REI-F08-PAIRED';OUT=ROOT/'runs/rei_fastest_v1/paired';BASE=ROOT/'docs/atomic_reionization_handoff_20261004_v1/runtime_returns/evidence/F08_successors'
summary=json.loads((OUT/'campaign_summary.json').read_text());assert summary['status']=='PRESCRIBED_DISCRETE_PAIRED_HISTORY_INDEPENDENT_PASS' and summary['runs']==15
BASE.mkdir(exist_ok=False)
def write(name,value):(BASE/name).write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n')
manifest=json.loads((OUT/'source_manifest.json').read_text());scenario='configs/rei_fastest_v1/science_scenario_v1.json';identity={'scenario':scenario,'scenario_sha256':hashlib.sha256((ROOT/scenario).read_bytes()).hexdigest(),'campaign_summary':'runs/rei_fastest_v1/paired/campaign_summary.json','source_manifest':'runs/rei_fastest_v1/paired/source_manifest.json'}
u={'task_id':'REI-SPECTRAL-U-WORK','state':'completed','scope':'Derived native consumer interface from actual independently checked F08; no new campaign','input_identity':identity,'native_interface':{'owner':'PairedState/PairedTrial and paired_history summary_json','N':'sum energy-node counts + lower_guard_n','U':'sum energy-node counts*physical_energy_eV + lower_guard_u','units':{'N':'photons per H nucleus','U':'eV per H nucleus','time':'normal/proper seconds','w':'eV per H nucleus'},'characteristic':'r=g(q,t1)/g(q,t0), g=sqrt(sum q_i^2 exp(-2H_i t)); qhat fixed; physical direction evolves','transport':'positive linear energy deposition; total N conserved; U_old-U_transport belongs to radiation redshift work','source':'dt*5e-15 photons/H at13.7eV; normalized proper-isotropic Jacobian1/(V*g^3)','lower_guard':'N retained, U redshifted, no photoabsorption below10eV; no duplicate edge loss','upper_guard':'unimplemented export raises an error; not reached by this nonnegative-H source/window','photo_owner':'same attenuation event owns N removal, E absorption, chi binding and E-chi photoheat','escape_owner':'Case-A RR/DR escape-energy ledger; no diffuse photon count inferred','thermal_owner':'gas2Hmean*w once; distinct from radiation characteristic work'},'balances':{'N':'N_final + absorbed_N - source_N - N_initial','U':'w + binding + escape + photon_U + radiation_redshift_work + gas_thermal_work - source_U - initial_total_U'},'frozen_acceptance':{'local_strict_lt':2e-4,'public_width_strict_lt':2e-3,'step_and_final_conservation_limit':1e-12},'independent_basis':'All actual full/half1/inherited half2 stages independently checked MPFI200; reported events and final checkpoints bound','N_only_interface':'original flrw_three_equations::photon_balance remains N-only; its PASS is not a U/history certificate','continuum_projection_error_bound':'NOT_ESTABLISHED','physical_fit_model_error':'NOT_MEASURED','scientific_admission':'HOLD'};write('U_EDGE_WORK_CONTRACT.json',u)
write('BASS_ELECTRON_HISTORY_INPUT.json',{'task_id':'BASS-REI-EXP01','state':'INPUT_PAYLOAD_RETURNED_RECEIVER_EXECUTION_PENDING','input_identity':identity,'files':'runs/rei_fastest_v1/paired/consumer_inputs/*-electron_density.csv.gz','coordinates':'initial t=0 row from immutable S0 IC, then actual accepted normal-time endpoints; proper nH/nHe/ne cm^-3','electron_law':'native binary nH*xHII + native binary nHe*(xHeII+2*xHeIII)','gas_frame':'homogeneous gas rest frame; S0 tilt zero','D':'1 for normal observer in selected S0; receiver must apply any separately selected Doppler factor exactly once','bounds':'conditional on actual binary stage density; gas fractions from uniform stage boxes; not continuum density/physical uncertainty','interval_s':[0,1e13],'observer_tail':'NOT_PROVIDED; no zero tail assumption','Thomson_cross_section':'RECEIVER_SOURCE_AUTHORITY_REQUIRED','receiver_visibility_executed':False,'scientific_admission':'HOLD'})
write('CR_OFF_DISPATCH_OBSERVATION.json',{'task_id':'CR-OFF-DISPATCH-OBSERVATION','state':'blocked','input_identity':identity,'selected_native_entrypoint':'paired_history::run/run_one -> paired_trial -> endpoint -> FT03 primary stage','CR_flag_authority':scenario+'#atomic_model.CR=OFF','declared_processes':'HG RR/CI + two DR terms + primary PI; HH/RCT/CR absent in declared model','actual_campaign_source_identities':manifest,'dynamic_CR_load_provider_callback_counters':'NOT_OBSERVED','blocker':'The selected typed native dispatcher exposes no CR loader/provider/callback seam or dynamic counter. OFF metadata and absence from the chemistry model do not constitute runtime callback observation.','next_executable_condition':'Use an actually selected CR-capable dispatcher and instrument its concrete provider/callback seam, without replaying F08 just to observe an unrelated callback','CR_negligibility':'NOT_MEASURED','baseline_validity_blocked':False,'scientific_admission':'HOLD'})
# Reuse four already certified actual macrosteps instead of a new FLRW07 run.
record=next(x for x in manifest if x['run']=='T0_FLRW');raw=ROOT/record['raw_preserved_local_path'];prefix=[]
with raw.open() as file:
 for _ in range(4):prefix.append(json.loads(next(file)))
assert all(x['accepted'] for x in prefix);write('FLRW07_ACTUAL_F08_PREFIX.json',{'task_id':'REI-CHAT-FLRW07_EXPANDING_SPLIT_STEP_REGRESSION','state':'BOUNDED_COMPOSITION_RETURN_REUSED_FROM_COMPLETED_F08','input_identity':identity,'run_source_identity':record,'header':'runs/rei_fastest_v1/paired/receipts/T0_FLRW-header.jsonl','certified_macrosteps':4,'actual_records':prefix,'independent_proofs':'T0_FLRW whole-history component receipt; original complete8000 trial phase plus targeted checkpoint closeout','new_native_or_science_dispatches':0,'birth_rule':'Source birth time/E13.7 and qhat measure reconstructible from stage audit/header; subsequently represented by declared fixed-energy projection','retained_birth_cohorts':'NOT_TRACKED_AFTER_DECLARED_ENERGY_PROJECTION; no exact-cohort transport claim','scientific_admission':'HOLD'})
# Export a precise accepted F05 stage, leaving the external25-output computation to CR.
f05=ROOT/'runs/rei_fastest_v1/first_interval/level_0_transactions.jsonl.gz'
with gzip.open(f05,'rb') as file:first=file.readline()
r=json.loads(first);assert r['accepted'] and r['t0_s']==0 and r['dt_s']==1e9
write('CR_F04E_ACCEPTED_F05_STAGE_INPUT.json',{'task_id':'CR-F04E-EVENT-JET-RECEIVER-BINDING','state':'EXACT_ACCEPTED_INPUT_RETURNED_RECEIVER_BINDING_PENDING','input_identity':{'F05_return':'docs/atomic_reionization_handoff_20261004_v1/runtime_returns/REI-F05.json','raw_source':'runs/rei_fastest_v1/first_interval/level_0_transactions.jsonl.gz','record_sha256':hashlib.sha256(first).hexdigest(),'source_identity':'runs/rei_fastest_v1/first_interval/source_identity.dat'},'accepted_record':r,'coordinate_units':{'site_centres':'xHII,xHeII,xHeIII,w_eV_per_H,N0_per_H,N1_per_H,N2_per_H','old_state_and_state':'fractions3,u_erg_cm3,proper_photon_counts3,escape_erg_cm3'},'stage_density_cm3':{'nH':1e-4,'nHe':8.3e-6},'packet_energy_eV':[20.,35.,70.],'model_constructor':'Ft03Model::controlled() inherits HHeModel::controlled_fixture(); original source identity retained','geometry':'Static H=0 F05 fixture; not expanding S0','time_endpoints_s':{'FULL_BE_ENDPOINT':1e9,'HALF1_BE_ENDPOINT':5e8,'HALF2_BE_ENDPOINT':1e9},'HALF2_incoming':'HALF1 centre/box; no independent initial-state reset','external_CR25_output_map_executed':False,'uniform_event_escape_remainders':'UNRESOLVED_EXTERNAL_GATE_RETAINED','scientific_admission':'HOLD'})
write('SUCCESSOR_DAG_STATE.json',{'F08':'SCOPED_NUMERICAL_COMPLETED','U_EDGE_WORK':'DERIVED_CONTRACT_COMPLETED_FROM_ACTUAL_F08','FLRW07':'ACTUAL_CERTIFIED_PREFIX_RETURNED_NO_REPLAY','BASS_EXP01':'ACTUAL_ELECTRON_INPUT_RETURNED_RECEIVER_EXECUTION_PENDING','CR_OFF_OBSERVATION':'BLOCKED_NO_SELECTED_DYNAMIC_COUNTER_SEAM','CR_F04E':'EXACT_F05_INPUT_RETURNED_RECEIVER_BINDING_PENDING','HE_F3_DOMAIN':'BLOCKED_EMPTY_COMMON_DOMAIN','F09':'BLOCKED_OPTIONAL_BINDING_AND_COMMON_DOMAIN','L01':'DORMANT_NO_SELECTED_EXTENSION','direct_chat_delivery':'UNDELIVERED_NO_BROWSER_AVAILABLE','scope':'Current return overlay only; historical/shared owner receipts remain unchanged'})
print(json.dumps({'status':'SCOPED_SUCCESSOR_INPUTS_WRITTEN','files':[x.name for x in BASE.iterdir()],'new_science_campaigns':0}))
