//! Local-host/boot/inode-scoped two-transition NORMAL-domain accepted-record bridge.
//! Frozen-panel checkpoints, cross-run roots and BE records have different schemas and refuse.
use crate::{record::{self,W,D},coupled::State,radiation::Grid,Fallible,err};
use rei_microphysics::igm_config::HistoryConfig;
use std::{fs::{self,File,OpenOptions},io::{Read,Write},path::Path,process::{Command,Stdio}};
#[path="run_identity.rs"]mod run_identity;
include!("build_identity.rs");
pub const MAGIC_V1:&[u8]=b"REI_COUPLED_MIDPOINT_ACCEPTED_RECORD_V1\n";
pub const MAGIC_V2:&[u8]=b"REI_COUPLED_MIDPOINT_ACCEPTED_RECORD_V2\n";
pub const MAGIC:&[u8]=b"REI_COUPLED_MIDPOINT_ACCEPTED_RECORD_V3\n";
const MAX:usize=16*1024*1024;
const CONFIG:&str=include_str!("../../long-flrw/configs/igm_manufactured_z12_to10.cfg");
pub fn sha(bytes:&[u8])->Fallible<String>{let mut p=Command::new("sha256sum").stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().map_err(err)?;let write=p.stdin.take().ok_or("SHA_INPUT")?.write_all(bytes);let out=p.wait_with_output().map_err(err)?;write.map_err(err)?;if !out.status.success(){return Err("SHA_FAILED".into())}let s=String::from_utf8(out.stdout).map_err(err)?;let h=s.split_whitespace().next().ok_or("SHA_OUTPUT")?;if h.len()!=64||!h.bytes().all(|b|b.is_ascii_digit()||(b'a'..=b'f').contains(&b)){return Err("SHA_FORMAT".into())}Ok(h.into())}
pub struct Context{pub bytes:Vec<u8>,pub initial_y:[f64;4]}
impl Context{pub fn new(cfg:&HistoryConfig,grid:&Grid,initial_y:[f64;4])->Self{let mut w=W(Vec::new());w.text(BUILD_PIN);w.text(CONFIG);w.text(record::AUTHORITY);w.n(192);w.n(2);w.a(&[cfg.start,cfg.end,cfg.max_dln_a,cfg.min_dln_a,cfg.temperature_k,cfg.source.photons_per_h_per_s,cfg.source.energy_min_ev,cfg.source.energy_max_ev]);w.a(&cfg.fractions);w.a(&initial_y);w.n(grid.base as u64);w.n(grid.order as u64);w.n(grid.nodes.len()as u64);for(e,q)in &grid.nodes{w.a(&[*e,*q])}Self{bytes:w.0,initial_y}}}
fn bounded(path:&Path,cap:usize)->Fallible<Vec<u8>>{let m=fs::symlink_metadata(path).map_err(err)?;if !m.file_type().is_file()||m.len()>cap as u64{return Err("FILE_CAP_OR_SYMLINK".into())}let mut b=Vec::new();File::open(path).map_err(err)?.take(cap as u64+1).read_to_end(&mut b).map_err(err)?;if b.len()>cap{return Err("READ_CAP".into())}Ok(b)}
fn envelope(payload:Vec<u8>)->Fallible<Vec<u8>>{let mut b=MAGIC.to_vec();b.extend(sha(&payload)?.as_bytes());b.push(b'\n');b.extend(payload);if b.len()>MAX{return Err("CHECKPOINT_CAP".into())}Ok(b)}
fn encode(ctx:&Context,namespace:&str,attempt:u64,state:&State,initial:f64)->Fallible<Vec<u8>>{let mut w=W(Vec::new());w.n(ctx.bytes.len()as u64);w.0.extend(&ctx.bytes);w.text(namespace);w.n(attempt);w.f(initial);record::write_state(&mut w,state);envelope(w.0)}
fn decode(bytes:&[u8],ctx:&Context,namespace:&str,cfg:&HistoryConfig,grid:&Grid)->Fallible<(State,f64,u64)>{let(version,magic)=if bytes.starts_with(MAGIC){(3,MAGIC)}else if bytes.starts_with(MAGIC_V2){(2,MAGIC_V2)}else if bytes.starts_with(MAGIC_V1){(1,MAGIC_V1)}else{return Err("MIDPOINT_SCHEMA_ONLY_NO_FROZEN_PROMOTION".into())};if bytes.len()>MAX{return Err("CHECKPOINT_CAP".into())}let t=&bytes[magic.len()..];if t.len()<65||t[64]!=b'\n'||sha(&t[65..])?.as_bytes()!=&t[..64]{return Err("CHECKSUM".into())}let mut d=D{b:&t[65..],i:0};let n=d.size(1024*1024)?;if d.take(n)?!=ctx.bytes.as_slice(){return Err("EXACT_SOURCE_GAS_GRID_CLOCK_CONTEXT".into())}if d.text(65536)?!=namespace{return Err("NAMESPACE_CONTEXT".into())}let attempt=d.n()?;let initial=d.f()?;let state=match version{1=>record::read_state_v1(&mut d)?,2=>record::read_state_v2(&mut d)?,_=>record::read_state(&mut d)?};if d.i!=d.b.len(){return Err("TRAILING_RECORD".into())}record::verify_state(cfg,grid,&state,ctx.initial_y)?;let expected=ctx.initial_y[3]+crate::material::binding(ctx.initial_y,state.accepted_records[0].midpoint_background[4]/state.accepted_records[0].midpoint_background[3]);
 // The accepted initial material is checked against exact caller bits in Store::resume too.
 // Mathematically constant nHe/nH can differ by binary64 stage; no normalization is applied.
 if !initial.is_normal()||expected<=0.{return Err("INITIAL_MATERIAL_DOMAIN".into())}Ok((state,initial,attempt))}
pub struct Store{run:run_identity::Run,generation:usize,attempt:u64,head_hash:Option<String>}
impl Store{
 pub fn create(root:&Path)->Fallible<Self>{Ok(Self{run:run_identity::Run::create(root)?,generation:0,attempt:0,head_hash:None})}
 pub fn resume(root:&Path,ctx:&Context,cfg:&HistoryConfig,grid:&Grid,expected_initial:f64)->Fallible<(Self,State)>{let run=run_identity::Run::resume(root)?;let bytes=bounded(&run.root.join("HEAD"),MAX)?;let(state,initial,attempt)=decode(&bytes,ctx,&run.namespace,cfg,grid)?;if initial.to_bits()!=expected_initial.to_bits(){return Err("INITIAL_MATERIAL_BITS".into())}let generation=state.accepted_records.len();let hash=sha(&bytes)?;let mut latest=0;let mut serial=0;
  for e in fs::read_dir(&run.root).map_err(err)?{let e=e.map_err(err)?;let name=e.file_name().to_string_lossy().into_owned();if let Some(g)=name.strip_prefix("committed-"){let g=g.parse::<usize>().map_err(err)?;if g==0||g>2{return Err("COMMIT_SCHEMA".into())}latest=latest.max(g);}if let Some(a)=name.strip_prefix("attempt-"){let a=a.parse::<u64>().map_err(err)?;if bounded(&e.path(),65536)?!=run.namespace.as_bytes(){return Err("ATTEMPT_NAMESPACE".into())}serial=serial.max(a.checked_add(1).ok_or("LEASE_EXHAUSTED")?);}}
  if latest!=generation||bounded(&run.root.join(format!("committed-{generation}")),256)?!=hash.as_bytes(){return Err("CHECKPOINT_REPLAY_OR_INCOMPLETE_COMMIT".into())}if serial<=attempt||bounded(&run.root.join(format!("attempt-{attempt}")),65536)?!=run.namespace.as_bytes(){return Err("MISSING_COMMITTED_LEASE".into())}
  Ok((Self{run,generation,attempt:serial,head_hash:Some(hash)},state))}
 pub fn publish(&mut self,ctx:&Context,cfg:&HistoryConfig,grid:&Grid,state:&State,initial:f64)->Fallible<bool>{self.run.check_owner()?;if state.accepted_records.len()!=self.generation+1||state.accepted_records.len()>2{return Err("ACCEPTED_RECORD_REPLAY".into())}if let Some(h)=&self.head_hash{let bytes=bounded(&self.run.root.join("HEAD"),MAX)?;if &sha(&bytes)?!=h{return Err("STALE_HEAD".into())}let(old,_,_)=decode(&bytes,ctx,&self.run.namespace,cfg,grid)?;if !record::same_records(&state.accepted_records[..self.generation],&old.accepted_records)||!record::bits_eq(&state.accepted_records[self.generation].y0,&old.y){return Err("ACCEPTED_PREFIX_REPLAY".into())}}
  record::verify_state(cfg,grid,state,ctx.initial_y)?;let attempt=self.attempt;let bytes=encode(ctx,&self.run.namespace,attempt,state,initial)?;let(restored,ii,aa)=decode(&bytes,ctx,&self.run.namespace,cfg,grid)?;if record::science_image(&restored)!=record::science_image(state)||record::state_bytes(&restored)!=record::state_bytes(state)||ii.to_bits()!=initial.to_bits()||aa!=attempt{return Err("ENCODER_TYPED_ROUNDTRIP".into())}
  self.attempt=self.attempt.checked_add(1).ok_or("LEASE_EXHAUSTED")?;let mut lease=OpenOptions::new().write(true).create_new(true).open(self.run.root.join(format!("attempt-{attempt}"))).map_err(err)?;lease.write_all(self.run.namespace.as_bytes()).map_err(err)?;lease.sync_all().map_err(err)?;
  let pending=self.run.root.join(format!("pending-{attempt}"));let mut f=OpenOptions::new().write(true).create_new(true).open(&pending).map_err(err)?;f.write_all(&bytes).map_err(err)?;f.sync_all().map_err(err)?;File::open(&self.run.root).map_err(err)?.sync_all().map_err(err)?;let hash=sha(&bytes)?;fs::rename(&pending,self.run.root.join("HEAD")).map_err(err)?;
  // Rename publishes. Never return a rollback-shaped Err after this boundary.
  self.generation=state.accepted_records.len();self.head_hash=Some(hash.clone());let marker=(||->std::io::Result<()>{let mut f=OpenOptions::new().write(true).create_new(true).open(self.run.root.join(format!("committed-{}",self.generation)))?;f.write_all(hash.as_bytes())?;f.sync_all()?;File::open(&self.run.root)?.sync_all()})();Ok(marker.is_ok())
 }
}
