import pathlib,json,hashlib,zipfile
r=pathlib.Path(__file__).resolve().parent;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();proof=json.loads((r/'evidence/IMMUTABILITY_AND_SOURCE_PROOF.json').read_text());assert sha(r/'src/ledger_sidecar.rs')==proof['new_source_sha256'];assert '15 passed; 0 failed'in(r/'logs/final-accepted-green.stdout').read_text();assert 'PASS'in(r/'evidence/REVIEW.md').read_text()
js=[json.loads(p.read_text())for p in(r/'results').glob('*.json')];cpu=sum(x['cpu_s']for x in js);wall=sum(x['wall_s']for x in js);assert cpu+10<90 and wall+15<150
footprint=sum(p.stat().st_size for p in r.rglob('*')if p.is_file());temp_roots=list(pathlib.Path('/tmp').glob('rei-ledger-test-*'));temp_size=sum(p.stat().st_size for root in temp_roots for p in root.rglob('*')if p.is_file());assert footprint+temp_size<256*1048576
resources={'measured_commands_before_package':len(js),'measured_child_CPU_s_before_package':cpu,'measured_execution_wall_s_before_package':wall,'unmetered_review_admin_CPU_reserve_s':10,'unmetered_review_admin_execution_wall_reserve_s':15,'review_measured_reads_wall_s_included_in_reserve':5.609364505,'dispatch_elapsed_excluded':True,'per_process_compile_AS_bytes':2048*1048576,'per_process_numeric_AS_bytes':512*1048576,'numeric_observed_RSS_target_bytes':256*1048576,'numeric_sampled_peak_RSS_bytes':max(x['sampled_group_peak_rss_bytes']for x in js if x['as_limit_bytes']==512*1048576),'compile_sampled_peak_RSS_bytes':max(x['sampled_group_peak_rss_bytes']for x in js if x['as_limit_bytes']==2048*1048576),'numeric_peak_is_sampled_not_a_hard_RSS_cap':True,'workspace_footprint_bytes_before_package':footprint,'retained_failed_fixture_roots':len(temp_roots),'retained_failed_fixture_bytes':temp_size,'unreaped_killed_compile_descendant_CPU_covered_by_reserve':True}
(r/'evidence/RESOURCE_SUMMARY.json').write_text(json.dumps(resources,indent=2));state=json.loads((r/'STATE.json').read_text());state['focused_review']='PASS conditional ledger plumbing; no blocking defect';state['package_date']='2026-10-08';(r/'STATE.json').write_text(json.dumps(state,indent=2))
files=[p for p in sorted(r.rglob('*'))if p.is_file()and 'target'not in p.relative_to(r).parts and '__pycache__'not in p.relative_to(r).parts and p.name!='PACKAGE_MANIFEST.json']
manifest=[{'path':str(p.relative_to(r)),'bytes':p.stat().st_size,'sha256':sha(p)}for p in files];(r/'PACKAGE_MANIFEST.json').write_text(json.dumps(manifest,indent=2));files.append(r/'PACKAGE_MANIFEST.json')
z=r.parent/'REI_CANONICAL_LEDGER_ADMISSION_SOURCE_ONLY_20261008.zip'
with zipfile.ZipFile(z,'w',zipfile.ZIP_DEFLATED,compresslevel=6)as out:
 for p in files:out.write(p,str(pathlib.Path(r.name)/p.relative_to(r)))
with zipfile.ZipFile(z)as q:assert q.testzip()is None
receipt={'path':str(z),'bytes':z.stat().st_size,'sha256':sha(z),'members':len(files),'crc_verified':True,'target_excluded':True,'sibling_dependency_archive_sha256':'4700d68ffda7204656fbd57d80c56a60278afb9bf0d03d1cd9c697298e0acd3f','scope':'CONDITIONAL_BOOKKEEPING_ONLY','physical_admission':'HOLD'}
(r.parent/'CANONICAL_LEDGER_ADMISSION_PACKAGE_RECEIPT.json').write_text(json.dumps(receipt,indent=2));print(json.dumps(receipt,indent=2))
