use short_hhe_control::{coupled,durable,err,material,output,record::{self,D,W},radiation::{self,Grid},diagnostics::Density,Fallible};
use rei_microphysics::{audit_counts,igm_config::{parse_config,HistoryConfig},verner_cutoff_ev,HHeModel};
use std::{fs::{self,File,OpenOptions},io::Write,path::Path,sync::atomic::Ordering};
#[path="../../../source/rei-next-nodes/short-hhe-midpoint/src/run_identity.rs"] mod run_identity;
const CONFIG:&str=include_str!("../../../source/rei-next-nodes/long-flrw/configs/igm_manufactured_z12_to10.cfg");
const OLD_MAGIC:&[u8]=b"REI_DURATION_UNPROJECTED_NATIVE_STATE_V1\n";
const MAGIC:&[u8]=b"REI_PROGRESSIVE_APPEND_SUPPORT_CHECKPOINT_V3\n";
const OLD_EXE:&str="171d08b42cd5dad158584fad56a429af4a6a8eff748a4a776b2dcc8e1f3e4d81";
const OLD_SHA:&str="85407e44a25a521767fc16c10a43e3df0e9883f8d95ea85c1fde8f5c4fcbb312";
const OLD64_SHA:&str="c719008ed2a6d17863738c761e7381f9a595284d874ebf1cf7fa914718628cf6";
const CTX_SHA:&str="e74580584a74ad4bddc4c65933a8454a8a6cbde965623f75affa9ee6b745b6fb";
const SEED_SHA:&str="9929edc36232b3620264f3a8b3cf55104ba31c4f63df238f02ed25079738b2b0";
fn counts()->[usize;3]{let(a,b)=audit_counts::read();[a,b,coupled::EVALUATIONS.load(Ordering::Relaxed)]}
fn delta(a:[usize;3],b:[usize;3])->[usize;3]{std::array::from_fn(|i|b[i]-a[i])}
fn read(p:&Path)->Fallible<Vec<u8>>{let m=fs::symlink_metadata(p).map_err(err)?;if !m.is_file()||m.len()>32*1024*1024{return Err("FILE_CAP".into())}fs::read(p).map_err(err)}
fn payload<'a>(b:&'a[u8],magic:&[u8])->Fallible<&'a[u8]>{if !b.starts_with(magic){return Err("SCHEMA".into())}let e=&b[magic.len()..];if e.len()<65||e[64]!=b'\n'||durable::sha(&e[65..])?.as_bytes()!=&e[..64]{return Err("CHECKSUM".into())}Ok(&e[65..])}
fn atom(root:&Path,b:&[u8])->Fallible<()>{let mut f=OpenOptions::new().write(true).create_new(true).open(root.join("HEAD.next")).map_err(err)?;f.write_all(b).map_err(err)?;f.sync_all().map_err(err)?;fs::rename(root.join("HEAD.next"),root.join("HEAD")).map_err(err)?;File::open(root).and_then(|f|f.sync_all()).map_err(err)}
fn parse_context(bytes:&[u8],depth:usize)->Fallible<(Grid,[f64;3],usize)>{
 if depth>8{return Err("CONTEXT_DEPTH".into())}let mut d=D{b:bytes,i:0};let version=d.text(256)?;let parent_sha=d.text(256)?;let parent_ctx_sha=d.text(256)?;if d.text(256)?!="e34740bf7972cc4bd9223373024450fdb85dab25331e8354e1273701134c2cd0"{return Err("SOURCE_BUILD".into())}let size=d.size(1024*1024)?;let prior=d.take(size)?;let prior_grid=if version=="APPEND_CONTEXT_V2"{if parent_sha!=OLD_SHA||parent_ctx_sha!=CTX_SHA||durable::sha(prior)?!=CTX_SHA{return Err("ANCESTRAL_CONTEXT".into())}None}else if version=="APPEND_CONTEXT_V3"{if parent_sha.len()!=64||durable::sha(prior)?!=parent_ctx_sha{return Err("PARENT_CONTEXT_CHAIN".into())}Some(parse_context(prior,depth+1)?)}else{return Err("CONTEXT_SCHEMA".into())};let size=d.size(1024*1024)?;let mut g=D{b:d.take(size)?,i:0};if g.text(256)?!="OLD_PREFIX_APPEND_POSITIVE_GAUSS4_V1"{return Err("GRID_RULE".into())}let count=g.size(4096)?;let intervals=g.size(4096)?;let base=g.size(512)?;let order=g.size(4)?;let mut nodes=Vec::new();for _ in 0..count{let[x,w]=g.a()?;if w<=0.||nodes.last().is_some_and(|p:&(f64,f64)|p.0>=x){return Err("GRID_POSITIVITY_ORDER".into())}nodes.push((x,w));}if g.i!=g.b.len()||base!=512||order!=4{return Err("GRID_SCHEMA".into())}let values=d.a::<3>()?;let n=d.size(96)?;if d.i!=d.b.len()||![24,48,96].contains(&n)||values[1]<=values[0]{return Err("CONTEXT_CLOCK".into())}if let Some((prior,clock,_))=prior_grid{if nodes.len()<prior.nodes.len()||nodes[..prior.nodes.len()]!=prior.nodes[..]||values[0].to_bits()!=clock[1].to_bits()||values[2].to_bits()!=clock[2].to_bits(){return Err("ANCESTRAL_GRID_EPOCH_PREFIX".into())}for(x,_)in &nodes[prior.nodes.len()..]{if *x-100f64.ln()<=values[0]{return Err("ANCESTRAL_ZERO_PREHISTORY".into())}}}Ok((Grid{nodes,intervals,base,order},values,n))
}
fn parent_state(root:&Path,pinfile:&Path)->Fallible<(coupled::State,f64,Grid,f64,Vec<u8>,String)>{let pin=String::from_utf8(read(pinfile)?).map_err(err)?;let lines=pin.lines().collect::<Vec<_>>();if lines.len()!=4{return Err("PIN_MANIFEST".into())}let bytes=read(&root.join("HEAD"))?;let ctx=read(&root.join("CONTEXT.bin"))?;if durable::sha(&bytes)?!=lines[0]||durable::sha(&ctx)?!=lines[1]{return Err("PIN_PARENT_STATE_CONTEXT".into())}let mut version_reader=D{b:&ctx,i:0};let version=version_reader.text(256)?;if !((lines[3]=="V2"&&version=="APPEND_CONTEXT_V2")||(lines[3]=="V3"&&version=="APPEND_CONTEXT_V3")){return Err("MANIFEST_CONTEXT_SCHEMA_MISMATCH".into())}let (grid,times,n)=parse_context(&ctx,0)?;let run=run_identity::Run::resume(root)?;let magic=if lines[3]=="V2"{b"REI_APPEND_ONLY_SOURCE_SUPPORT_CHECKPOINT_V2\n".as_slice()}else if lines[3]=="V3"{MAGIC}else{return Err("PARENT_SCHEMA".into())};let (k,e,state)=decode_magic(&run,&ctx,lines[2],&grid,times[0],times[1],n,&bytes,magic)?;if k!=n||state.s.to_bits()!=times[1].to_bits(){return Err("PARENT_MUST_ACCEPTED_ENDPOINT".into())}Ok((state,e,grid,times[2],ctx,lines[0].to_string()))}

fn rule(a:f64,b:f64)->Vec<(f64,f64)>{let d=(6f64/5.).sqrt();let x=((3.-2.*d)/7.).sqrt();let y=((3.+2.*d)/7.).sqrt();let wi=(18.+30f64.sqrt())/36.;let wo=(18.-30f64.sqrt())/36.;[(-y,wo),(-x,wi),(x,wi),(y,wo)].into_iter().map(|(v,w)|(a+(b-a)*0.5*(1.+v),(b-a)*0.5*w)).collect()}
fn append(cfg:&HistoryConfig,old:&Grid,a:f64,b:f64,panels:usize)->Fallible<(Grid,f64,f64)>{
 if ![16,32].contains(&panels)||a.to_bits()!=(cfg.start+cfg.max_dln_a).to_bits()||b<=a||b>cfg.end{return Err("APPEND_PREMISE".into())}
 let lo=a+cfg.source.energy_max_ev.ln();let hi=b+cfg.source.energy_max_ev.ln();let mut cuts=vec![lo,hi];
 for j in 0..=96{let t=a+(b-a)*j as f64/96.;for e in [cfg.source.energy_min_ev,cfg.source.energy_max_ev,verner_cutoff_ev(radiation::SPECIES[0]),verner_cutoff_ev(radiation::SPECIES[1]),verner_cutoff_ev(radiation::SPECIES[2])]{let x=t+e.ln();if lo<x&&x<hi{cuts.push(x)}}}cuts.sort_by(f64::total_cmp);cuts.dedup();if panels==32{let mut refined=Vec::new();for ab in cuts.windows(2){let m=(ab[0]+ab[1])*0.5;if !(ab[0]<m&&m<ab[1]){return Err("TAIL_REFINEMENT_GEOMETRY".into())}refined.push(m);}cuts.extend(refined);cuts.sort_by(f64::total_cmp);cuts.dedup();}let mut grid=old.clone();grid.intervals+=cuts.len()-1;
 for ab in cuts.windows(2){for(x,w)in rule(ab[0],ab[1]){if !(x>ab[0]&&x<ab[1]&&w>0.&&x>lo&&x-cfg.source.energy_max_ev.ln()>a){return Err("ZERO_PREHISTORY_OR_POSITIVE_CELL".into())}grid.nodes.push((x,w));}}
 if grid.nodes.len()>4096{return Err(format!("APPEND_CODEC_LIVE_SAMPLE_CAP: old={} added={} total={} cap=4096",old.nodes.len(),grid.nodes.len()-old.nodes.len(),grid.nodes.len()))}if grid.nodes[..old.nodes.len()]!=old.nodes[..]{return Err("APPEND_PREFIX_CHANGED".into())}Ok((grid,lo,hi))
}
fn support(cfg:&HistoryConfig,a:f64,b:f64,lo:f64,hi:f64)->Fallible<()>{if !(lo<=cfg.start+cfg.source.energy_min_ev.ln()&&hi>=b+cfg.source.energy_max_ev.ln()&&a>=cfg.start&&b<=cfg.end){return Err("MISSING_SOURCE_SUPPORT".into())}Ok(())}
fn grid_bytes(g:&Grid)->Vec<u8>{let mut w=W(vec![]);w.text("OLD_PREFIX_APPEND_POSITIVE_GAUSS4_V1");w.n(g.nodes.len()as u64);w.n(g.intervals as u64);w.n(g.base as u64);w.n(g.order as u64);for(x,y)in &g.nodes{w.a(&[*x,*y])}w.0}
fn extend(s:&coupled::State,g:&Grid)->Fallible<coupled::State>{let old=record::state_bytes(s);let mut n=s.clone();n.density.resize_zeros(g.nodes.len());let mut check=n.clone();check.density.truncate(s.density.len());if record::state_bytes(&check)!=old||n.density[s.density.len()..].iter().any(|x|x.to_bits()!=0){return Err("EXACT_STATE_ZERO_EXTENSION".into())}Ok(n)}
fn context(ctx:&[u8],parent_sha:&str,g:&Grid,a:f64,b:f64,n:usize,initial:f64)->Fallible<Vec<u8>>{let mut w=W(vec![]);w.text("APPEND_CONTEXT_V3");w.text(parent_sha);w.text(&durable::sha(ctx)?);w.text("e34740bf7972cc4bd9223373024450fdb85dab25331e8354e1273701134c2cd0");w.n(ctx.len()as u64);w.0.extend(ctx);let gb=grid_bytes(g);w.n(gb.len()as u64);w.0.extend(gb);w.a(&[a,b,initial]);w.n(n as u64);parse_context(&w.0,0)?;Ok(w.0)}
fn clock(a:f64,b:f64,k:usize,n:usize)->f64{if k==0{a}else if k==n{b}else{a+(b-a)*k as f64/n as f64}}
fn decode_magic(run:&run_identity::Run,c:&[u8],exe:&str,g:&Grid,a:f64,b:f64,n:usize,bytes:&[u8],magic:&[u8])->Fallible<(usize,f64,coupled::State)>{run.check_owner()?;if bytes.len()>2*1024*1024{return Err("NEW_ENVELOPE_CAP".into())}let mut d=D{b:payload(bytes,magic)?,i:0};if d.text(65536)?!=run.namespace||d.text(256)?!=exe{return Err("NEW_NAMESPACE_EXE".into())}let nn=d.size(2*1024*1024)?;if d.take(nn)?!=c{return Err("NEW_GRID_SUPPORT_CONTEXT".into())}let k=d.size(n)?;let e=d.f()?;let s=record::read_state(&mut d)?;if d.i!=d.b.len()||s.s.to_bits()!=clock(a,b,k,n).to_bits()||s.density.len()!=g.nodes.len()||!s.accepted_records.is_empty(){return Err("NEW_EPOCH_STATE".into())}Ok((k,e,s))}
fn decode(run:&run_identity::Run,c:&[u8],exe:&str,g:&Grid,a:f64,b:f64,n:usize,bytes:&[u8])->Fallible<(usize,f64,coupled::State)>{decode_magic(run,c,exe,g,a,b,n,bytes,MAGIC)}
fn restore(run:&run_identity::Run,c:&[u8],exe:&str,g:&Grid,a:f64,b:f64,n:usize)->Fallible<(usize,f64,coupled::State)>{decode(run,c,exe,g,a,b,n,&read(&run.root.join("HEAD"))?)}
fn save(run:&run_identity::Run,c:&[u8],exe:&str,g:&Grid,a:f64,b:f64,n:usize,k:usize,e:f64,s:&coupled::State)->Fallible<()>{let mut w=W(vec![]);w.text(&run.namespace);w.text(exe);w.n(c.len()as u64);w.0.extend(c);w.n(k as u64);w.f(e);record::write_state(&mut w,s);let mut bytes=MAGIC.to_vec();bytes.extend(durable::sha(&w.0)?.bytes());bytes.push(b'\n');bytes.extend(w.0);let(pk,pe,ps)=decode(run,c,exe,g,a,b,n,&bytes)?;if pk!=k||pe.to_bits()!=e.to_bits()||record::state_bytes(&ps)!=record::state_bytes(s){return Err("PREPUBLICATION_CODEC_STATE".into())}atom(&run.root,&bytes)?;let(kk,ee,ss)=restore(run,c,exe,g,a,b,n)?;if kk!=k||ee.to_bits()!=e.to_bits()||record::state_bytes(&ss)!=record::state_bytes(s){return Err("NEW_TYPED_ROUNDTRIP".into())}Ok(())}
fn integral(cfg:&HistoryConfig,a:f64,b:f64,n:usize,tail:bool)->Fallible<f64>{let h=(b-a)/n as f64;let mut sum=0.;for i in 0..=n{let s=a+h*i as f64;let p=cfg.background.at_ln_a(s).map_err(err)?;let fraction=if tail{((1./(cfg.source.energy_max_ev*(a-s).exp())-1./cfg.source.energy_max_ev)/(1./cfg.source.energy_min_ev-1./cfg.source.energy_max_ev)).max(0.)}else{1.};let f=cfg.source.photons_per_h_per_s/p.hubble_per_s*fraction;sum+=f*if i==0||i==n{1.}else if i%2==1{4.}else{2.};}Ok(sum*h/3.)}
fn write_row(f:&mut File,row:&[f64;41])->Fallible<()>{output::write_row(f,row)}

const NEW_MAGIC_V1:&[u8]=b"REI_CANONICAL_PARTIAL_CHECKPOINT_V1\n";
const NEW_MAGIC_V2:&[u8]=b"REI_CANONICAL_PARTIAL_CHECKPOINT_V2\n";
const NEW_MAGIC:&[u8]=b"REI_CANONICAL_PARTIAL_CHECKPOINT_V3\n";
fn flat(g:&Grid,t:[f64;3],n:usize)->Vec<u8>{let mut w=W(vec![]);w.text("FLAT_ACCEPTED_CONTEXT_V1");w.n(g.nodes.len()as u64);w.n(g.intervals as u64);w.n(g.base as u64);w.n(g.order as u64);for(x,y)in &g.nodes{w.a(&[*x,*y]);}w.a(&t);w.n(n as u64);w.0}
fn unflat(b:&[u8])->Fallible<(Grid,[f64;3],usize)>{let mut d=D{b,i:0};if d.text(256)?!="FLAT_ACCEPTED_CONTEXT_V1"{return Err("FLAT_SCHEMA".into())}let size=d.size(8192)?;let intervals=d.size(8192)?;let base=d.size(512)?;let order=d.size(4)?;let mut nodes=vec![];for _ in 0..size{let[x,w]=d.a()?;if w<=0.||nodes.last().is_some_and(|p:&(f64,f64)|p.0>=x){return Err("GRID_DOMAIN".into())}nodes.push((x,w));}let times=d.a()?;let n=d.size(96)?;if d.i!=b.len()||![48,96].contains(&n){return Err("FLAT_CLOCK".into())}Ok((Grid{nodes,intervals,base,order},times,n))}
fn canonical_write(w:&mut W,s:&coupled::State)->Fallible<()>{let l=short_hhe_control::v2::owner_ledger(s.radiation).map_err(err)?;for i in 0..13{w.wide(l.terms[i].value);w.wide(l.terms[i].loss);w.n(l.occurrence[i]);w.wide(l.coefficient[i]);}for x in s.active_loss{w.wide(x)}Ok(())}
fn canonical_read(d:&mut D,s:&mut coupled::State)->Fallible<()>{use canonical::{Tracked,Wide};let old=short_hhe_control::v2::owner_ledger(s.radiation).map_err(err)?;let mut terms=[Tracked::empty();13];let mut occurrence=[0;13];let mut coefficient=[Wide::ZERO;13];for i in 0..13{terms[i]=Tracked{value:d.wide()?,loss:d.wide()?};occurrence[i]=d.n()?;coefficient[i]=d.wide()?;if occurrence[i]>0&&(terms[i].loss.is_empty()||coefficient[i].is_empty()){return Err("MISSING_OWNER_LOSS_OR_COEFFICIENT".into())}}let l=short_hhe_control::v2::OwnerLedger{terms,occurrence,coefficient,heat:old.heat,heat_occurrence:old.heat_occurrence,heat_coefficient:old.heat_coefficient};s.radiation.canonical=Some(l);s.active_loss=[d.wide()?,d.wide()?];if short_hhe_control::v2::owner_ledger(s.radiation).map_err(err)?!=l{return Err("CANONICAL_READOUT_STATE_MISMATCH".into())}Ok(())}
fn new_save(root:&Path,c:&[u8],k:usize,e:f64,s:&coupled::State)->Fallible<()>{let mut w=W(vec![]);w.n(c.len()as u64);w.0.extend(c);w.n(k as u64);w.f(e);record::write_state(&mut w,s);canonical_write(&mut w,s)?;let mut b=NEW_MAGIC.to_vec();b.extend(durable::sha(&w.0)?.bytes());b.push(b'\n');b.extend(w.0);if b.len()>16*1024*1024{return Err("CHECKPOINT_CAP_16MIB".into())}let(_,kk,ee,ss)=new_decode(&b)?;let mut x=W(vec![]);let mut y=W(vec![]);canonical_write(&mut x,s)?;canonical_write(&mut y,&ss)?;if kk!=k||ee.to_bits()!=e.to_bits()||record::state_bytes(s)!=record::state_bytes(&ss)||x.0!=y.0{return Err("CANONICAL_ROUNDTRIP".into())}atom(root,&b)}
fn pair_legacy_density(s:&mut coupled::State,g:&Grid)->Fallible<()>{use canonical::Tracked;let c=HHeModel::controlled_fixture();let mut nodes=Vec::with_capacity(g.nodes.len());for (&(eta,_),&number) in g.nodes.iter().zip(s.density.iter()){let n=Tracked::from_f64(number).map_err(err)?;let energy=n.scale(c.ev_erg*(eta-s.s).exp()).map_err(err)?;nodes.push(short_hhe_control::diagnostics::PhotonNode{number:n,energy});}s.density.replace_canonical(nodes).map_err(err)}
fn new_decode(b:&[u8])->Fallible<(Vec<u8>,usize,f64,coupled::State)>{let(version,magic)=if b.starts_with(NEW_MAGIC){(3,NEW_MAGIC)}else if b.starts_with(NEW_MAGIC_V2){(2,NEW_MAGIC_V2)}else if b.starts_with(NEW_MAGIC_V1){(1,NEW_MAGIC_V1)}else{return Err("CANONICAL_CHECKPOINT_SCHEMA".into())};let mut d=D{b:payload(b,magic)?,i:0};let nn=d.size(16*1024*1024)?;let c=d.take(nn)?.to_vec();let(g,t,n)=unflat(&c)?;let k=d.size(n)?;let e=d.f()?;let mut s=match version{1=>record::read_state_v1(&mut d)?,2=>record::read_state_v2(&mut d)?,_=>record::read_state(&mut d)?};canonical_read(&mut d,&mut s)?;if version==1{pair_legacy_density(&mut s,&g)?}if d.i!=d.b.len()||s.s.to_bits()!=clock(t[0],t[1],k,n).to_bits()||s.density.len()!=g.nodes.len()||!s.accepted_records.is_empty(){return Err("NEW_ACCEPTED_CLOCK".into())}Ok((c,k,e,s))}
fn migrate_partial(parent:&Path,root:&Path,n:usize)->Fallible<(Vec<u8>,usize,f64,coupled::State)>{let b=read(&parent.join("HEAD"))?;let ctx=read(&parent.join("CONTEXT.bin"))?;let expected=match parent.file_name().and_then(|x|x.to_str()){Some("h0008-coarse")=>"44f19648bcf13971f51c68fe3c2021ecd469ad0574d6387a8422865da0a8a6a7",Some("h0008-fine-diagnostic")=>"d05c0d519a2cdb628ec449d35955666a1b334efac79ac0ab20a34e7685e276b7",Some("h0008-tail-diagnostic")=>"877550c6cfef949504beb9dd09ee432d229ced2853013f8825962511a10ba1c3",_=>return Err("UNDECLARED_PARTIAL_SOURCE".into())};if durable::sha(&b)?!=expected{return Err("PINNED_IMMUTABLE_PARTIAL_HEAD".into())}let(g,t,pn)=parse_context(&ctx,0)?;if pn!=n{return Err("PARTIAL_STEP_COUNT".into())}let mut d=D{b:payload(&b,MAGIC)?,i:0};let _ns=d.text(65536)?;let exe=d.text(256)?;let receipt=String::from_utf8(read(&parent.join("MIGRATION.json"))?).map_err(err)?;if !receipt.contains(&format!("\"exe_sha\":\"{exe}\"")){return Err("PARTIAL_SOURCE_EXE".into())}let len=d.size(16*1024*1024)?;if d.take(len)?!=ctx{return Err("PARTIAL_CONTEXT".into())}let k=d.size(n)?;let e=d.f()?;let mut s=record::read_state_v1(&mut d)?;pair_legacy_density(&mut s,&g)?;if d.i!=d.b.len()||k==0||k>=n||s.s.to_bits()!=clock(t[0],t[1],k,n).to_bits()||s.density.len()!=g.nodes.len()||!s.accepted_records.is_empty(){return Err("PARTIAL_STATE_DOMAIN".into())}let c=flat(&g,t,n);fs::create_dir(root).map_err(err)?;new_save(root,&c,k,e,&s)?;fs::write(root.join("CONTEXT.bin"),&c).map_err(err)?;fs::write(root.join("MIGRATION.json"),format!("{{\"old_head_sha\":{:?},\"old_context_sha\":{:?},\"old_exe_sha\":{:?},\"partial_step\":{},\"n\":{},\"gas_epoch_grid_owners_preserved\":true,\"historical_loss\":\"NOT_MEASURED_IN_OLD_BINARY64_CHECKPOINT\",\"old_cost_evidence_preserved\":true}}\n",durable::sha(&b)?,durable::sha(&ctx)?,exe,k,n)).map_err(err)?;Ok((c,k,e,s))}
fn run()->Fallible<()>{let args:Vec<_>=std::env::args().collect();if args.len()!=6{return Err("migrate-partial|resume parent newroot n end".into())}let mode=&args[1];let parent=Path::new(&args[2]);let root=Path::new(&args[3]);let n:usize=args[4].parse().map_err(err)?;let end:usize=args[5].parse().map_err(err)?;let mut cfg=parse_config(CONFIG).map_err(err)?;record::set_enabled(false);let before=counts();let(c,first,mut elapsed,mut state)=if mode=="migrate-partial"{migrate_partial(parent,root,n)?}else if mode=="resume"{new_decode(&read(&root.join("HEAD"))?)?}else{return Err("MODE".into())};let(grid,t,nn)=unflat(&c)?;if nn!=n||end<first||end>n||counts()!=before{return Err("PURE_MIGRATION_OR_STEP_RANGE".into())}cfg.max_dln_a=t[1]-cfg.start;let mut history=OpenOptions::new().write(true).create_new(true).open(root.join(format!("history_{first}_{end}.csv"))).map_err(err)?;writeln!(history,"{}",output::HEADER).map_err(err)?;let mut steps=File::create(root.join(format!("steps_{first}_{end}.csv"))).map_err(err)?;writeln!(steps,"k,s,norm,n_ratio,e_ratio,RHS,sigma,evaluations").map_err(err)?;let mut maxima=[state.norm,state.n_ratio,state.e_ratio];let engine=counts();for k in first+1..=end{let target=clock(t[0],t[1],k,n);let c0=counts();let old=record::state_bytes(&state);let next=match coupled::advance(&cfg,&grid,&state,target,t[2]){Ok(x)=>x,Err(e)=>{if record::state_bytes(&state)!=old{return Err("REJECTED_STATE_CHANGED".into())}fs::write(root.join(format!("FAILURE_{k}.json")),format!("{{\"reason\":{:?},\"last_epoch\":{:?},\"last_step\":{},\"attempted_step\":{},\"counts\":{:?},\"state_unchanged\":true}}\n",e,state.s,k-1,k,delta(c0,counts()))).map_err(err)?;return Err(e)}};let p=cfg.background.at_ln_a((state.s+next.s)*0.5).map_err(err)?;elapsed+=(next.s-state.s)/p.hubble_per_s;state=next;for(i,v)in[state.norm,state.n_ratio,state.e_ratio].into_iter().enumerate(){if v>1.||!v.is_finite(){return Err("ORIGINAL_GATE_WITH_CANONICAL_LOSS".into())}maxima[i]=maxima[i].max(v)}new_save(root,&c,k,elapsed,&state)?;let science=counts();let row=output::row(&cfg,&grid,&state,t[2])?;let observer=delta(science,counts());output::write_row(&mut history,&row)?;history.flush().map_err(err)?;writeln!(steps,"{k},{:.17e},{:.17e},{:.17e},{:.17e},{},{},{}",state.s,state.norm,state.n_ratio,state.e_ratio,delta(c0,counts())[0],delta(c0,counts())[1],delta(c0,counts())[2]).map_err(err)?;steps.flush().map_err(err)?;println!("ACCEPTED k={k} observer={observer:?} Gamma_representation_bound={:?} gates={:?}",*radiation::LAST_GAMMA_BOUND.lock().map_err(err)?,[state.norm,state.n_ratio,state.e_ratio]);}
 let row=output::row(&cfg,&grid,&state,t[2])?;let mut f=File::create(root.join(format!("endpoint_{end}.csv"))).map_err(err)?;writeln!(f,"{}",output::HEADER).map_err(err)?;output::write_row(&mut f,&row)?;
 let ni=integral(&cfg,t[0],state.s,128,false)?;let mean=HHeModel::controlled_fixture().ev_erg*(cfg.source.energy_max_ev/cfg.source.energy_min_ev).ln()/(1./cfg.source.energy_min_ev-1./cfg.source.energy_max_ev);
 // Source comparison includes old accepted prefix of this horizon; preserve original base.
 let receipt=format!("{{\"first_step\":{},\"last_step\":{},\"new_advances\":{},\"nodes\":{},\"n\":{},\"epoch\":{:?},\"redshift\":{:?},\"elapsed_s\":{:?},\"maximum_original_gate_ratios_including_new_loss\":{:?},\"counts\":{:?},\"phase_counts_with_observer\":{:?},\"source_simpson128\":{:?},\"source_mean_energy_erg\":{:?},\"old_historical_loss\":\"NOT_MEASURED\",\"physical_claim\":\"HOLD\"}}\n",first,end,end-first,grid.nodes.len(),n,state.s,row[1],elapsed,maxima,counts(),delta(engine,counts()),ni,mean);fs::write(root.join(format!("PHASE_{first}_{end}.json")),&receipt).map_err(err)?;println!("{receipt}");Ok(())}
fn main(){if let Err(e)=run(){eprintln!("CANONICAL_REFUSAL {e}; COUNTS={:?}",counts());std::process::exit(2)}}
