from pathlib import Path
import hashlib,json
r=Path(__file__).resolve().parent
repos={
 'BASS_HE':{'sha':'eae1d2209fd9a555bea461032f272c7c7c19766e','branch':'research/shared-c64-crossrepo-20260928','pr':17},
 'bass_cr':{'sha':'c277bb4305ccddf5b5d94f83f59f398e7f6c3b62','branch':'research/r4q-gap-closure-20261001','pr':23},
 'WU088_HH':{'sha':'47accb0b3ac9adca40913dc06c797a509c1a7b49','branch':'research/r31ao-unequal-order-ladder-20260930','pr':33}}
ident=[]
for repo,meta in repos.items():
 tree={x['path']:x for x in json.loads((r/'raw'/f'{repo}_tree.json').read_text())['tree']}
 # AGENTS was fetched before source selection.
 p=r/'sources'/repo/'AGENTS.md';p.parent.mkdir(parents=True,exist_ok=True)
 if not p.exists():p.write_bytes((r/'raw'/f'{repo}_agents.md').read_bytes())
 for p in (r/'sources'/repo).rglob('*'):
  if not p.is_file():continue
  rp=str(p.relative_to(r/'sources'/repo));b=p.read_bytes();x=tree[rp]
  def gh(b):return hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest()
  if gh(b)!=x['sha'] and b.endswith(b'\n') and gh(b[:-1])==x['sha']:p.write_bytes(b[:-1]);b=b[:-1]
  assert gh(b)==x['sha'],rp
  ident.append({'repo':repo,'commit':meta['sha'],'path':rp,'bytes':len(b),'blob':gh(b),'sha256':hashlib.sha256(b).hexdigest()})
(r/'SOURCE_IDENTITIES.json').write_text(json.dumps({'exact_blob_matches':len(ident),'files':ident},indent=2)+'\n')
base='docs/atomic_reionization_handoff_20261004_v1/threads/'
scope=[
 {'lane':'F08_S0','model':'FT03 finite fixed-energy paired histories','temperature_domain_K':[35000,60000],'temperature_domain_authority':'prior F08 source contract; root REI intake must independently bind current manifest','RCT':'OFF','HH':'OFF control preserved','CR':'OFF scope; integrated legacy history callback count not established here','new_IGM_certificate_transfer':False,'physical_admission':False},
 {'lane':'HE_FAST_REJOIN01','model':'actual IGM point RHS plus separate conditional RCT source','consumer_commit':'dbb54009a517242ff5a41c805512471a74dd25f4','IGM_operational_K':[1,1000000],'KF96_operational_K':[1000,10000000],'GM25_operational_K':[200,10000],'common_operational_K':[1000,10000],'domain_is_empirical_accuracy':False,'baseline_RCT':'OFF','ON_research':'13 native tests, 56 finite points completed in addon; owner history adoption open','rate_moment':None,'physical_admission':False},
 {'lane':'CR_F0_IGM','model':'source-pinned instantaneous photon-to-IGM point bridge','consumer_commit':'dbb54009a517242ff5a41c805512471a74dd25f4','CR_mode':'OFF only','ON':'refused before computation','scoped_witness_load_calls':0,'scoped_witness_callbacks':0,'actual_production_global_counts':None,'owner_import_ACK':None,'native_unique_tests':23,'native_points':6,'physical_admission':False,'F04P_certificate_transfers_to_IGM':False},
 {'lane':'HH_ON05B_TH05','model':'FT03 plus LCS same moving cohorts, short prefix','HH_research':'ACTIVE; inherited activation, no renewed permission gate','canonical_S0':'OFF unchanged','time_s':[0,800000000000],'epsilon':[-0.01,0.01],'lambda':[0,1],'TH05_scope':'each positive lambda versus OFF; strict HII and nonnegative cohort survival difference','ON06_live_source_consistent_integration':'OPEN_RESERVED_OWNER','IGM_transfer':False,'physical_admission':False,'total_ne_positive_difference_proved':False}]
state={
 'schema':'sync03.atomic-intake.v1','observed_utc_window':'2026-10-07T11:01Z onward','repos':repos,'read_only':True,'scientific_suite_reruns':0,'source_blob_matches':len(ident),
 'supersession_corrections':[
  {'repo':'BASS_HE','stale':'CURRENT_FASTEST_STATE still reports F08 not executed and old HE-F2C/latest component','authoritative_additive_successor':base+'BASS_HE/runs/HE-FAST-REJOIN01_20261007/FASTEST_REJOIN_STATE.json','correction':'New IGM point common-domain obstacle resolved, original FT03 common domain still empty; short history and F09 not completed. STEP06 full current library build at its recorded pin completed; no repeat generic compile blocker.'},
  {'repo':'bass_cr','stale':'SYNC02 handoff sets F04E next','authoritative_additive_successor':'docs/fastest_track_resume_20261005_v1/F04E_NATIVE_RECEIVER_BINDING_KO.md','correction':'F04E actual F05 binding and subsequent F04F through F04P completed in declared scopes. Latest CR_F0 bridge native candidate done; owner import/global history OFF counters remain open.'},
  {'repo':'WU088_HH','stale':'CURRENT_SYNC_STATE WAITING_ON_REI_DOMAIN and prior SYNC02 parked label','authoritative_additive_successor':base+'WU088_HH/theory_th05_20261007_v1/RESULT_SUMMARY.json','correction':'HH research ACTIVE, ON05B finite matched histories and TH05 exact-real signed response done. ON06 actual point/interval/root/model/checkpoint pilot open. Canonical S0 OFF unchanged.'}],
 'active_owner_exclusions':['HE-FAST-REJOIN02 owner common-domain history/integrator adoption','CR-F0 owner import/callsite and global history witness','HH-ON06 coherent native integration; HH terminal-group regularity theory if already owned','REI IGM boundary/midpoint/long-history solver code'],
 'applicability':scope,
 'blockers':[
  {'repo':'BASS_HE','baseline_blocker':False,'optional_blockers':['owner selected integrator adoption','actual stage EOS-T within [1000,10000] K','explicit escape-energy closure with absent physical moment','17-fold nominal coefficient discrepancy']},
  {'repo':'bass_cr','baseline_blocker':False,'optional_blockers':['actual owner import and source callsite integration','global history CR loader/callback instrumentation remains null'],'legacy':['G02 UNRESOLVED','production HOLD','capture false','all_bound OPEN','b_grid NO_GO']},
  {'repo':'WU088_HH','baseline_blocker':False,'optional_blockers':['source-consistent native ON06 integration','tiny four-path contrast not continuum certified'],'backup_gap':'ON05B recovery core dual backed, full raw 413950057-byte archive not dual backed; do not count core backup as full raw backup','legacy':['24/289 accepted','265 unbounded','epsilon_C null','epsilon_R null','B22 OPEN']}],
 'verification':'read exact pinned source bytes and compare Git blob identities; received upstream test counts, did not rerun or newly independently review their science',
 'instruction_note':'bass_cr AGENTS references .codex/readback-policy.json absent from fetched tree; docs/READBACK_POLICY.md present and read. No external mutation performed.',
 'second_loop_assessment':{'actual_optional_ne_trajectory_available_in_this_intake':False,'new_IGM_uniform_optional_ne_cap_available':False,'recommended':'Use actual F08 accepted history plus its scoped boxes for a representation-explicit opacity transfer and refinement study, or actual admitted short IGM histories for baseline tau. Do not manufacture optional ON response from point competition ratios.','theory':'At fixed same density/clock, delta ne=nH delta xHII+nHe(delta xHeII+2 delta xHeIII); |delta tau|<=c sigmaT integral B_ne dt. For positive opacity, |delta exp(-tau)|<=exp(-min(tau1,tau2))*|delta tau|. These are conditional transfer inequalities; an actual stage-valid B_ne and interpolation/time-error contract are required for a numerical certificate.','cautions':['RCT direct electron source zero does not imply zero coupled electron-history change','TH05 Delta HII>0 alone does not prove total ne sign because helium changes','Same-t zero-tilt Thomson opacity does not produce directional dependence merely from a Bianchi label','Pointwise or endpoint boxes alone do not certify unknown continuous trajectory between stored rows']}}
(r/'ATOMIC_INTAKE.json').write_text(json.dumps(state,indent=2,ensure_ascii=False)+'\n')
tasks=[
 {'id':'SYNC03_BASS_F08_RECEIVER','status':'READY_ROOT_RUNNING','owner':'SYNC03 BASS consumer','input':['actual F08 proper-ne accepted histories plus identity and uncertainty metadata','source-pinned BASS visibility clock API'],'output':['source-bound tau/visibility receiver CSV and plot','unit/clock/tail and numerical error ledger'],'owner_excludes':['REI integrator core','HE integrator addon','CR import','HH ON06'],'acceptance':['proper densities cm^-3 to m^-3 once','D and c applied once','tail explicit','all source identities recorded','discrete and continuum claims separated']},
 {'id':'SYNC03_OBSERVABLE_TRANSFER','status':'READY_AFTER_RECEIVER_INPUT_CONTRACT','owner':'SYNC03 independent theory/consumer','input':['loop1 accepted receiver contract and actual F08 rows','existing source-bound finite boxes or explicit reported input intervals'],'output':['conditional transfer proof','discrete optical-depth envelope and paired refinement analysis if finite input boxes available','otherwise preserve NOT_CERTIFIED continuous budget'],'owner_excludes':['new optional ON trajectory','new integrator','existing owner source/provider changes'],'acceptance':['no endpoint-to-continuum inference','species covariance and density ownership explicit','do not import FT03 theory into IGM','match declared cell interpolation to actual code','reject unknown physical total-tau tail']},
 {'id':'SYNC03_OPTIONAL_ADMISSION_MATRIX','status':'READY_LIGHTWEIGHT_PARALLEL','owner':'SYNC03 synchronization','input':['this source-pinned latest atomic intake','root actual REI F08/new-IGM source manifest'],'output':['machine-readable baseline/OFF/optional applicability matrix','per-thread owner-reserved tasks and supersession pointers'],'owner_excludes':['mutating stale owner status files','activating HH/RCT/CR in baseline','rerunning completed point suites'],'acceptance':['HH remains ACTIVE in own research lane','HE old FT03 empty/new IGM nonempty distinguished','CR candidate zero counters/global null distinguished','original physical/legacy gates and failures retained']},
 {'id':'HE_FAST_REJOIN02','status':'RESERVED_EXISTING_OWNER','input':['HE-FAST-REJOIN01 addon','owner selected integrator/model/IC/Ebar/budget'],'output':['short common-domain optional RCT history and stage temperature guard'],'owner_excludes':['SYNC03 root implementing second generic integrator'],'acceptance':['actual EOS T every stage in [1000,10000]','source-specific rate/Ebar provenance','baseline OFF preserved']},
 {'id':'CR_F0_OWNER_IMPORT','status':'RESERVED_EXISTING_OWNER','input':['3129089fe0f52739961cefc65cda71ccce0a07ab','prepared receiver patch and five scientific module hashes'],'output':['owner-integrated source-driven callsite and actual history counters'],'owner_excludes':['new generic bridge redesign'],'acceptance':['preserve photon birth/redshift/stage ownership','no double photoheat','OFF no callback/load evidence at actual boundary']},
 {'id':'HH_ON06','status':'RESERVED_EXISTING_OWNER','input':['ON05B and TH05 source-bound returns','actual F08 point/thermal/intervalJet/root/model/checkpoint source'],'output':['coherent bounded ON pilot'],'owner_excludes':['SYNC03 core modifications','new authorization gate'],'acceptance':['do not attach OFF certificate to ON','same source throughout point and interval paths','keep F09 single REI owner']}]
(r/'NEXT_TASKS.json').write_text(json.dumps({'schema':'sync03.atomic-tasks.v1','tasks':tasks},indent=2,ensure_ascii=False)+'\n')
print(json.dumps({'source_files':len(ident),'tasks':len(tasks),'intake':str(r/'ATOMIC_INTAKE.json')}))
