import pathlib,json,hashlib,zipfile
r=pathlib.Path(__file__).resolve().parent;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();proof=json.loads((r/'evidence/IMMUTABILITY_AND_REAL_CALLER_PROOF.json').read_text());assert sha(r/'src/lib.rs')==proof['new_caller_sha256'];assert sha(r/'tests/real_native_receiver.rs')==proof['new_test_sha256'];assert 'PASS'in(r/'evidence/TARGETED_REVIEW.md').read_text()
old=[json.loads(p.read_text())for p in(r.parent/'rei-ledger-admission-v1/results').glob('*.json')];new=[json.loads(p.read_text())for p in(r/'results').glob('*.json')];cpu=sum(x['cpu_s']for x in old+new);wall=sum(x['wall_s']for x in old+new);assert cpu+13<90 and wall+20<150
footprint=sum(p.stat().st_size for p in r.rglob('*')if p.is_file())+sum(p.stat().st_size for p in(r.parent/'rei-ledger-admission-v1').rglob('*')if p.is_file());assert footprint<256*1048576
resource={'allocation':'ORIGINAL_LEDGER_90CPU_150WALL_NOT_RESET','prior_measured_CPU_s':sum(x['cpu_s']for x in old),'prior_measured_execution_wall_s':sum(x['wall_s']for x in old),'added_measured_CPU_s_before_package':sum(x['cpu_s']for x in new),'added_measured_execution_wall_s_before_package':sum(x['wall_s']for x in new),'combined_measured_CPU_s_before_package':cpu,'combined_measured_execution_wall_s_before_package':wall,'all_old_and_new_reserved_CPU_s':13,'all_old_and_new_reserved_execution_wall_s':20,'remaining_CPU_after_all_reserves_before_package':90-cpu-13,'remaining_wall_after_all_reserves_before_package':150-wall-20,'dispatch_elapsed_excluded':True,'added_numeric_sampled_peak_RSS_bytes':max(x['sampled_group_peak_rss_bytes']for x in new if x['as_limit_bytes']==512*1048576),'added_compile_sampled_peak_RSS_bytes':max(x['sampled_group_peak_rss_bytes']for x in new if x['as_limit_bytes']==2048*1048576),'combined_slice_footprint_bytes':footprint,'old_control_reruns':0,'real_native_trial_executions':2,'actual_RHS':72,'actual_provider_calls':234,'added_caller_RHS':0}
(r/'evidence/REMAINING_RESOURCE_SUMMARY.json').write_text(json.dumps(resource,indent=2))
state={'phase':'TARGETED_REVIEW_PASS_REAL_NATIVE_CALLER_GREEN1_OF1','scope':'ISOLATED_OPT_IN_DIAGNOSTIC_CALLER','production_receiver_adoption':False,'physical_admission':'HOLD','old_fabricated_15controls_preserved_not_rerun':True,'actual_real_native_trials':2,'actual_RHS':72,'actual_provider_calls':234,'caller_added_RHS':0,'uploads':0,'global_cross_host_or_disk_only_restore_proven':False}
(r/'STATE.json').write_text(json.dumps(state,indent=2))
files=[p for p in sorted(r.rglob('*'))if p.is_file()and 'target'not in p.relative_to(r).parts and '__pycache__'not in p.relative_to(r).parts and p.name!='PACKAGE_MANIFEST.json'];manifest=[{'path':str(p.relative_to(r)),'bytes':p.stat().st_size,'sha256':sha(p)}for p in files];(r/'PACKAGE_MANIFEST.json').write_text(json.dumps(manifest,indent=2));files.append(r/'PACKAGE_MANIFEST.json')
z=r.parent/'REI_REAL_NATIVE_LEDGER_CALLER_SOURCE_ONLY_20261008.zip'
with zipfile.ZipFile(z,'w',zipfile.ZIP_DEFLATED,compresslevel=6)as out:
 for p in files:out.write(p,str(pathlib.Path(r.name)/p.relative_to(r)))
with zipfile.ZipFile(z)as q:assert q.testzip()is None
receipt={'path':str(z),'bytes':z.stat().st_size,'sha256':sha(z),'members':len(files),'crc_verified':True,'target_excluded':True,'sibling_dependency_archives':['74330ac71267f00afb05c21c4ea7d9a9dc9138b11dd2d0c82c7368960cc28aaf','4700d68ffda7204656fbd57d80c56a60278afb9bf0d03d1cd9c697298e0acd3f'],'physical_admission':'HOLD'}
(r.parent/'REAL_NATIVE_LEDGER_CALLER_PACKAGE_RECEIPT.json').write_text(json.dumps(receipt,indent=2));print(json.dumps(receipt,indent=2))
